version: 2

project_name: cymbal

builds:
  - id: cymbal
    main: .
    binary: cymbal
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CC=zig-cc-darwin-amd64
          - CXX=zig-cxx-darwin-amd64
      - goos: darwin
        goarch: arm64
        env:
          - CC=zig-cc-darwin-arm64
          - CXX=zig-cxx-darwin-arm64
      - goos: linux
        goarch: amd64
        env:
          - CC=zig-cc-linux-amd64
          - CXX=zig-cxx-linux-amd64
      - goos: linux
        goarch: arm64
        env:
          - CC=zig-cc-linux-arm64
          - CXX=zig-cxx-linux-arm64

archives:
  - id: cymbal
    ids:
      - cymbal
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
